services:
  Laboratory:
    build:
      context: .
    image: laboratory-client
    container_name: laboratory-client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Laboratory.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.Laboratory.entrypoints=websecure"
      - "traefik.http.routers.Laboratory.tls.certresolver=myresolver"
